Added checking if cmus is running

diff --git a/blayc b/blayc
--- a/blayc
+++ b/blayc
@@ -20,37 +20,47 @@ music=""
 # if cmus and cmus-remote exist on the user's system, you may prompt the user to
 # search for a song
 if command -v cmus > /dev/null && command -v cmus-remote > /dev/null; then
-    #read input from user (to search for song)
-    read -p " Play: " song_to_play
-    #remove spaces in the song and store the value in the $song variable
-    song=$(echo "$song_to_play" | sed 's/ /?/g')
-    #try to find the song in music directory
-    if [[ -n "$music" ]]; then
-        play=$(find "$music" -type f -iname "*$song*")
-    else
-        play=$(find $HOME/Music -type f -iname "*$song*")
-    fi
+    if [[ -n $(pidof cmus) ]]; then
+        #read input from user (to search for song)
+        read -p " Play: " song_to_play
+        #remove spaces in the song and store the value in the $song variable
+        song=$(echo "$song_to_play" | sed 's/ /?/g')
+        #try to find the song in music directory
+        if [[ -n "$music" ]]; then
+            play=$(find "$music" -type f -iname "*$song*")
+        else
+            play=$(find $HOME/Music -type f -iname "*$song*")
+        fi
 
-    case $play in
-        "")
-            #if the song doesn't exist, state that the song doesn't exist and
-            #exit the script
-            sleep 0.2
-            echo "Song not found :("	   
-            sleep 0.2
-            echo "Please refer to the README.md for more info."
-            sleep 3
-            ;;
+        case $play in
+            "")
+                #if the song doesn't exist, state that the song doesn't exist and
+                #exit the script
+                sleep 0.2
+                echo "Song not found :("	   
+                sleep 0.2
+                echo "Please refer to the README.md for more info."
+                sleep 3
+                ;;
 
-        *)
-            #if song exist, tell user it does, play it, and exit the script
-            echo "Song found!"
-            sleep 0.2
-            echo "Playing..."
+            *)
+                #if song exist, tell user it does, play it, and exit the script
+                echo "Song found!"
+                sleep 0.2
+                echo "Playing..."
+                sleep 0.3
+                cmus-remote -C "player-play $play"
+                ;;
+        esac
+        else
+            echo "Looks like cmus is not running."
             sleep 0.3
-            cmus-remote -C "player-play $play"
-            ;;
-    esac
+            echo "Start cmus and try again."
+            sleep 0.3
+            echo "Please refer to the README.md for more info."
+            sleep 5
+            exit 4
+    fi
 else
     #if cmus and cmus remote were not found, then try to install the program
     #NOTE: WILL ONLY INSTALL FOR DEBIAN BASED SYSTEMS
